# development:
#   adapter: postgresql
#   encoding: unicode
#   database: database_name
#   pool: 2
#   username: your_username
#   password: your_password
# production:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   host: <%= ENV['DATABASE_HOST'] %>
#   database: <%= ENV['DATABASE_NAME'] %>
#   username: <%= ENV['DATABASE_USER'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>

default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sinatra_development

test:
  <<: *default
  database: sinatra_test

production:
  <<: *default
  database: sinatra_production
