default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sinatra_development

test:
  <<: *default
  database: sinatra_test

production:
  <<: *default
  database: sinatra_production
